channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pandas=2.2.*
  - jupyterlab=4.2.*
  - ipywidgets=8.1.*
  - python-dotenv=1.0.*
  - yfinance=0.2.*
  - mplfinance=0.12.*
# [LangChain + LangGraph]
  - langchain=0.2.*
  - langchain-community=0.2.*
  - langchain-google-genai=1.0.*
  - langgraph=0.1.*